### ISSUE TITLE
List hours

### ISSUE THREAD

**Issue by ycanales** [eyscode/timetracker#3]
Similar to loading hours, listing them would be cool. I'd be glad to help if you think it's a useful addition.

**Comment by eyscode** [comment]
Actually that's a really useful feature that would be nice to have. Did you think how the new commands would look like? Maybe:
`tt load -t 'I did something awesome today' -d today` for loading hours
`tt show --from 04/01/2019 --to today` or even `tt show --last 3`? Feel free to open a PR!

**Comment by eyscode** [comment]
Implemented in `1.0.0` version.
