### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by mran3** [eyscode/timetracker#8]
Maybe is not the right place for this, but I really wanted to thank you for saving me hundreds of hours filling the same information on a form hour by hour during the first 90 days in a project.

**Comment by eyscode** [comment]
Thanks man I really appreciate those words! All of us wasted our time filling that form in the beginning, glad this project helps you and other people. Any PR is welcome! 

Having said that ^ I'm closing this since it's not an actual issue 😅

**Comment by AlexsanderAR** [comment]
+1
