### ISSUE TITLE
Support for no-focal projects

### ISSUE THREAD

**Issue by gaspo53** [eyscode/timetracker#9]
Current, timetracker doesn't support charging holidays, for example. If you define focal = '', it complains with:
`Error: Invalid value: Focal "" is not available. Choose from:`

And if you remove the key:
`Error: Invalid value: 'focal' missing in 'options' config option`

Can you add support for when no focal is provided in config?

**Comment by odarbelaeze** [comment]
👋🏼 @gaspo53 you should try the `--pto` flag.

**Comment by gaspo53** [comment]
Thanks
